# Netlify configuration for FADJMA Frontend
[build]
  base = "frontend/"
  command = "npm run build"
  publish = "build/"

[build.environment]
  REACT_APP_API_URL = "https://fadjma-backend.onrender.com"
  REACT_APP_ENVIRONMENT = "production"
  NODE_VERSION = "18"
  NPM_VERSION = "latest"

# SPA redirect for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy for development (optional)
[[redirects]]
  from = "/api/*"
  to = "https://fadjma-backend.onrender.com/api/:splat"
  status = 200
  force = true

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://fadjma-backend.onrender.com wss://fadjma-backend.onrender.com;"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Forms (if needed)
[forms]
  # Settings for forms

# Functions (if needed for serverless functions)
[functions]
  directory = "functions/"

# Build plugins
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Environment-specific settings
[context.production]
  command = "npm run build"

[context.deploy-preview]
  command = "npm run build"

[context.branch-deploy]
  command = "npm run build"

# Edge functions (optional)
[[edge_functions]]
  function = "auth"
  path = "/api/auth/*"